Repository GDSC-IIIT-Kalyani/Plot, pull requests merged in 2022-10, with the labels that each got.

#10 changed the cursor on canvas and added underlines in title elements
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest2022, level-2

#11 added save image functionality
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest2022, level-2

#13 Added colour boxes. Issue #5
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest2022, level-1, hacktoberfest-accepted, hacktoberfest-ready

#18 Revert "Added colour boxes. Issue #5"
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-ready

#14 Make website responsive
  index.html
  index.js
  style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest-ready

#20 Pull request for issue #1
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest2022, level-1, hacktoberfest-accepted, hacktoberfest-ready

#23 Improve the overall UI of the app
  .editorconfig
  assets/css/index.css
  assets/images/brush.png
  assets/images/bucket.png
  assets/images/bucket.svg
  assets/images/circle.svg
  assets/images/eraser.png
  assets/images/pencil.png
  assets/images/rectangle.svg
  assets/images/triangle.svg
  assets/js/app.js
  assets/js/index.js
  assets/js/utils.js
  index.html
  index.js
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest2022, level-3, hacktoberfest-accepted, hacktoberfest-ready

#26 fixes #24: relative path to image assets
  assets/css/index.css
  index.html
Labels: hacktoberfest, hacktoberfest2022, level-1, hacktoberfest-accepted, hacktoberfest-ready

#30 Add favicon
  assets/images/palette.png
  index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest-ready
